/*
프로그래머스 - https://school.programmers.co.kr/learn/courses/30/lessons/151139#qna

< 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기 >
*/
SELECT MONTH(START_DATE) AS MONTH, a.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), a.CAR_ID
HAVING RECORDS >= 1
ORDER BY MONTH(START_DATE), CAR_ID DESC